app/models/User.py
from app.extensions import db

class User(db.Model):
    id = db.Column(db.String, primary_key=True)
    name = db.Column(db.String(50))
    email = db.Column(db.String(50))
    password = db.Column(db.String(100))
    user_type = db.Column(db.Integer)

# from app.extensions import db
# from app.models.User import User
# db.create_all()

# Test `user_adm = User(id="123007", name="Daniela", email="dani@mail.com", password="dani123", user_type=1)`
# user_adm, user_adm.name

# db.session.add(user_adm)
# db.session.commit()   

app/__init__.py
# set FLASK_APP=app
# set FLASK_ENV=development
# set FLASK_DEBUG=1
# flask run

from flask import Flask
from config import Config
from app.extensions import db


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.config['SECRET_KEY'] = 'secret-key-goes-here'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'

    # Initialize Flask extensions here
    db.init_app(app)

    # Register blueprints here
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.profile import bp as profile_bp
    app.register_blueprint(profile_bp, url_prefix='/profile')

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp

@bp.route('/')
def index():
    return render_template('index.html')

app/profile/__init__.py
from flask import Blueprint

bp = Blueprint('profile', __name__)


from app.profile import routes

app/profile/routes.py
from flask import render_template
from app.profile import bp

@bp.route('/')
def profile():
    return render_template('profile/profile.html')

@bp.route('/dashboard/')
def dashboard():
    return render_template('profile/dashboard.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} - FlaskApp</title>
    <link rel="stylesheet" href="../static/css/base.css">
    {% block head %} {% endblock %}
</head>

<body>
    <!-- NAV BAR -->
    <header>
        <h2 class="logo"><a href="{{ url_for('main.index') }}">EcoTech Recycling</a></h2>
        <nav class="navigation">
            <a href="#map_section">Pontos de coleta</a>
            <a href="#pricing_section">Preços</a>
            <a href="#about_section">Sobre</a>
            <a href="{{ url_for('profile.profile') }}">Perfil</a>
            <a href="{{ url_for('auth.login') }}" class="active">Entrar</a>
        </nav>
    </header>

    <div class="content">
        {% block content %} {% endblock %}
    </div>

    <!-- Footer -->
    <footer id="footer">
        <div class="footer_container">
            <div class="footer_nav_links">
                <a href="#hero_section">Início</a>
                <a href="#map_section">Pontos de coleta</a>
                <a href="#pricing_section">Preços</a>
                <a href="#about_section">Sobre</a>
            </div>
            <div class="footer_left">
                <p>© 2024 EchoTech Recycling, LLC.</p>
            </div>
            <div class="footer_right">
                <a href="https://instagram.com"><img src="../static/img/footer/instagram.png" alt="Instagram"></a>
                <a href="https://web.facebook.com"><img src="../static/img/footer/facebook.png" alt="Facebook"></a>
                <a href="https://x.com/"><img src="../static/img/footer/twitter.png" alt="Twitter"></a>
                <p>contato@ecr.com</p>
            </div>
        </div>
    </footer>
</body>

</html>

app/templates/index.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="../static/css/index.css">
{% endblock %}

{% block content %}
<!-- Seção de Apresentação -->
<div id="banner">
    <h1 id="title">Promovemos uma<br>solução prática para o descarte<br>de resíduos eletrônicos, visando<br>um futuro mais limpo e consciente</h1>

</div>
 

<!-- Seção de Pontos de Coleta -->
<div id="map_section">
    <h2>Encontre pontos de coleta</h2>
    <div id="map_frame">
        <!-- <div class="aaa"></div> -->
        <iframe id="map" src="https://my.atlist.com/map/4245a69c-37c7-4abe-9f1c-f5cf228d6713/?share=true"
            allow="geolocation 'self' https://my.atlist.com" width="100%" height="400px" loading="lazy" frameborder="0"
            scrolling="no" allowfullscreen id="atlist-embed"></iframe>
    </div>
</div>

<!-- Seção de Tabela de Preços -->
<div id="pricing_section">
    <h2>Planos e Preços</h2>
    <div class="pricing_table">
        <div class="pricing_option">
            <h3>Experimental</h3>
            <p class="price">R$0<span>/cnpj</span></p>
            <ul>
                <li>Experimente por um mês</li>
            </ul>
            <a href="#" class="pricing_button">Escolher</a>
        </div>
        <div class="pricing_option">
            <h3>Mensal</h3>
            <p class="price">R$1000<span>/mês</span></p>
            <ul>
                <li>Suporte 24/7</li>
            </ul>
            <a href="#" class="pricing_button">Escolher</a>
        </div>
        <div class="pricing_option">
            <h3>Anual</h3>
            <p class="price">R$7.000<span>/ano</span></p>
            <ul>
                <li>Suporte 24/7</li>
            </ul>
            <a href="#" class="pricing_button">Escolher</a>
        </div>
    </div>
</div>

<!-- Seção de Sobre -->
<div id="about_section">
    <h2>Sobre Nós</h2>
    <div class="about_content">
        <div class="column">
            <h3>Por Que Escolher a Gente</h3>
            <ul>
                <li><strong>Facilidade e Comodidade:</strong> Solicite de casa, sem complicações.</li>
                <li><strong>Sustentabilidade:</strong> Contribuímos para um descarte ambientalmente responsável.</li>
                <li><strong>Conexão Eficiente:</strong> Facilitamos a logística para empresas de reciclagem.</li>
            </ul>
        </div>
        <div class="column">
            <h3>Como Funciona</h3>
            <ol>
                <li><strong>Solicite Coleta:</strong> Peça a coleta de lixo eletrônico através do nosso site ou app.</li>
                <li><strong>Gerenciamento de Tickets:</strong> Seu pedido se transforma em um ticket, visível para empresas cadastradas.</li>
                <li><strong>Coleta e Reciclagem:</strong> A empresa interessada assume o ticket, recolhe o lixo na sua casa e realiza a reciclagem correta.</li>
            </ol>
        </div>
    </div>
    <p>Conectamos você com empresas especializadas na coleta de lixo eletrônico de maneira rápida e sustentável.</p>
</div>



<!-- Seção de Fluxograma -->
<div id="flowchart_section">
    <h2>Como funciona?</h2>
    <img src="../static/img/home/fluxograma.png" alt="Fluxograma">
</div>


{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="../static/css/profile.css">
{% endblock %}

{% block content %}
<h1>PROFILE</h1>


{% endblock %}